/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.joyeriainventario.views;

/**
 *
 * @author ricar
 */
public class AddNewJewel extends javax.swing.JFrame {

    /**
     * Creates new form AddNewJewel
     */
    public AddNewJewel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jewelWeightTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jewelStockTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jewelMaterialTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jewelNameTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jewelPriceTxt = new javax.swing.JTextField();
        cancelJewelCreationBtn = new javax.swing.JButton();
        createJewelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(217, 234, 253));

        jPanel1.setBackground(new java.awt.Color(232, 249, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(248, 250, 252));
        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(49, 54, 63));
        jLabel1.setText("Stock:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        jewelWeightTxt.setBackground(new java.awt.Color(248, 250, 252));
        jewelWeightTxt.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jewelWeightTxt.setForeground(new java.awt.Color(49, 54, 63));
        jPanel1.add(jewelWeightTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 230, 20));

        jLabel2.setBackground(new java.awt.Color(248, 250, 252));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(49, 54, 63));
        jLabel2.setText("Crear Joya");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel3.setBackground(new java.awt.Color(248, 250, 252));
        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(49, 54, 63));
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jewelStockTxt.setBackground(new java.awt.Color(248, 250, 252));
        jewelStockTxt.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jewelStockTxt.setForeground(new java.awt.Color(49, 54, 63));
        jPanel1.add(jewelStockTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 230, 20));

        jLabel4.setBackground(new java.awt.Color(248, 250, 252));
        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(49, 54, 63));
        jLabel4.setText("Material:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jewelMaterialTxt.setBackground(new java.awt.Color(248, 250, 252));
        jewelMaterialTxt.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jewelMaterialTxt.setForeground(new java.awt.Color(49, 54, 63));
        jPanel1.add(jewelMaterialTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 230, 20));

        jLabel5.setBackground(new java.awt.Color(248, 250, 252));
        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(49, 54, 63));
        jLabel5.setText("Peso:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jewelNameTxt.setBackground(new java.awt.Color(248, 250, 252));
        jewelNameTxt.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jewelNameTxt.setForeground(new java.awt.Color(49, 54, 63));
        jewelNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jewelNameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(jewelNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 230, 20));

        jLabel6.setBackground(new java.awt.Color(248, 250, 252));
        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(49, 54, 63));
        jLabel6.setText("Precio:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jewelPriceTxt.setBackground(new java.awt.Color(248, 250, 252));
        jewelPriceTxt.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jewelPriceTxt.setForeground(new java.awt.Color(49, 54, 63));
        jPanel1.add(jewelPriceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 230, 20));

        cancelJewelCreationBtn.setBackground(new java.awt.Color(251, 251, 251));
        cancelJewelCreationBtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cancelJewelCreationBtn.setForeground(new java.awt.Color(49, 54, 63));
        cancelJewelCreationBtn.setText("Cancelar");
        cancelJewelCreationBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelJewelCreationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJewelCreationBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelJewelCreationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 90, 30));

        createJewelBtn.setBackground(new java.awt.Color(251, 251, 251));
        createJewelBtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        createJewelBtn.setForeground(new java.awt.Color(49, 54, 63));
        createJewelBtn.setText("Aceptar");
        createJewelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createJewelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJewelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(createJewelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jewelNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jewelNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jewelNameTxtActionPerformed

    private void cancelJewelCreationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJewelCreationBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelJewelCreationBtnActionPerformed

    private void createJewelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJewelBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createJewelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewJewel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewJewel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewJewel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewJewel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewJewel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelJewelCreationBtn;
    private javax.swing.JButton createJewelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jewelMaterialTxt;
    private javax.swing.JTextField jewelNameTxt;
    private javax.swing.JTextField jewelPriceTxt;
    private javax.swing.JTextField jewelStockTxt;
    private javax.swing.JTextField jewelWeightTxt;
    // End of variables declaration//GEN-END:variables
}
