/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.joyeriainventario.views;

/**
 *
 * @author ricar
 */
public class CreateSale extends javax.swing.JFrame {

    /**
     * Creates new form CreateSale
     */
    public CreateSale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jewelSaleCbx = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        customerSaleCbx = new javax.swing.JComboBox<>();
        totalAmountTxt = new javax.swing.JTextField();
        cancelSaleBtn = new javax.swing.JButton();
        addProductToOrderSaleBtn = new javax.swing.JButton();
        createSaleBtn2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordertItemsTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        quantitySaleTxt1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(232, 249, 255));
        setPreferredSize(new java.awt.Dimension(787, 490));

        jPanel1.setBackground(new java.awt.Color(232, 249, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(630, 273));
        jPanel1.setPreferredSize(new java.awt.Dimension(787, 490));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(248, 250, 252));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(49, 54, 63));
        jLabel2.setText("Nuevo Pedido de Venta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel6.setBackground(new java.awt.Color(248, 250, 252));
        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(49, 54, 63));
        jLabel6.setText("Joya");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jewelSaleCbx.setBackground(new java.awt.Color(248, 250, 252));
        jewelSaleCbx.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jewelSaleCbx.setForeground(new java.awt.Color(49, 54, 63));
        jewelSaleCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jewelSaleCbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 200, 20));

        jLabel7.setBackground(new java.awt.Color(248, 250, 252));
        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(49, 54, 63));
        jLabel7.setText("Cantidad");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, -1, -1));

        jLabel8.setBackground(new java.awt.Color(248, 250, 252));
        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(49, 54, 63));
        jLabel8.setText("Monto Total:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        customerSaleCbx.setBackground(new java.awt.Color(248, 250, 252));
        customerSaleCbx.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        customerSaleCbx.setForeground(new java.awt.Color(49, 54, 63));
        customerSaleCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(customerSaleCbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 200, 20));

        totalAmountTxt.setBackground(new java.awt.Color(248, 250, 252));
        totalAmountTxt.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        totalAmountTxt.setForeground(new java.awt.Color(49, 54, 63));
        jPanel1.add(totalAmountTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 70, 20));

        cancelSaleBtn.setBackground(new java.awt.Color(251, 251, 251));
        cancelSaleBtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cancelSaleBtn.setForeground(new java.awt.Color(49, 54, 63));
        cancelSaleBtn.setText("Cancelar");
        cancelSaleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelSaleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSaleBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelSaleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 120, 30));

        addProductToOrderSaleBtn.setBackground(new java.awt.Color(251, 251, 251));
        addProductToOrderSaleBtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        addProductToOrderSaleBtn.setForeground(new java.awt.Color(49, 54, 63));
        addProductToOrderSaleBtn.setText("Agregar");
        addProductToOrderSaleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addProductToOrderSaleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductToOrderSaleBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addProductToOrderSaleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, -1, 20));

        createSaleBtn2.setBackground(new java.awt.Color(251, 251, 251));
        createSaleBtn2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        createSaleBtn2.setForeground(new java.awt.Color(49, 54, 63));
        createSaleBtn2.setText("Crear pedido");
        createSaleBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createSaleBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSaleBtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(createSaleBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 120, 30));

        jScrollPane1.setBackground(new java.awt.Color(248, 250, 252));

        ordertItemsTable.setBackground(new java.awt.Color(248, 250, 252));
        ordertItemsTable.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ordertItemsTable.setForeground(new java.awt.Color(49, 54, 63));
        ordertItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ordertItemsTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 710, 300));

        jLabel9.setBackground(new java.awt.Color(248, 250, 252));
        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(49, 54, 63));
        jLabel9.setText("Cliente");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        quantitySaleTxt1.setBackground(new java.awt.Color(248, 250, 252));
        quantitySaleTxt1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        quantitySaleTxt1.setForeground(new java.awt.Color(49, 54, 63));
        jPanel1.add(quantitySaleTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 90, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelSaleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSaleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelSaleBtnActionPerformed

    private void addProductToOrderSaleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductToOrderSaleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addProductToOrderSaleBtnActionPerformed

    private void createSaleBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSaleBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createSaleBtn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateSale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductToOrderSaleBtn;
    private javax.swing.JButton cancelSaleBtn;
    private javax.swing.JButton createSaleBtn2;
    private javax.swing.JComboBox<String> customerSaleCbx;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jewelSaleCbx;
    private javax.swing.JTable ordertItemsTable;
    private javax.swing.JTextField quantitySaleTxt1;
    private javax.swing.JTextField totalAmountTxt;
    // End of variables declaration//GEN-END:variables
}
